// File generated by FlutterFire CLI & configured for Airotrack.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2gnFWXfFn_x135H86Hzyt1oNnkd6m9Xc',
    appId: '1:521325798783:web:airotrack-b67c4',
    messagingSenderId: '521325798783',
    projectId: 'airotrack-b67c4',
    authDomain: 'airotrack-b67c4.firebaseapp.com',
    storageBucket: 'airotrack-b67c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2gnFWXfFn_x135H86Hzyt1oNnkd6m9Xc',
    appId: '1:521325798783:android:8319344172fca2f457e64a',
    messagingSenderId: '521325798783',
    projectId: 'airotrack-b67c4',
    storageBucket: 'airotrack-b67c4.firebasestorage.app',
  );
}
